server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/image/ {
        alias /usr/share/nginx/images/;
    }

    location /api/ {
        proxy_pass http://spring:8070/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}